apiVersion: batch/v1
kind: CronJob
metadata:
  name: talentio-notifier-result
spec:
  schedule: "0 11,15 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: talentio-notifier
            resources:
              requests:
                cpu: 50m
                memory: 256M
              limits:
                cpu: 200m
                memory: 512M
            image: pyama/talentio-notifier:latest
            imagePullPolicy: Always
            env:
            - name: LANG
              value: C.UTF-8
            - name: TALENTIO_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: talentio-apikey
            - name: SLACK_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: slack-apikey
            - name: OPENAI_API_KEY_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: openai-apikey
            args:
            - "/bin/bash"
            - "-c"
            - "holiday_jp-go || bundle exec bin/talentio-notifier remind-result"
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: talentio-notifier-interview
spec:
  schedule: "*/10 * * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: talentio-notifier
            image: pyama/talentio-notifier:latest
            resources:
              requests:
                cpu: 50m
                memory: 256M
              limits:
                cpu: 200m
                memory: 512M
            env:
            - name: TALENTIO_SKIP_STAGE
              value: "3"
            - name: LANG
              value: C.UTF-8
            - name: TALENTIO_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: talentio-apikey
            - name: SLACK_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: slack-apikey
            - name: OPENAI_API_KEY_APIKEY
              valueFrom:
                secretKeyRef:
                  name: talentio-notifier-secret
                  key: openai-apikey
            args:
            - "/bin/bash"
            - "-c"
            - "holiday_jp-go || bundle exec bin/talentio-notifier remind-interview"
          restartPolicy: Never
